/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tuinascimento.locadoraveiculos.view;

import com.tuinascimento.locadoraveiculos.controller.ManterClienteController;
import com.tuinascimento.locadoraveiculos.utils.MaskUtils;

import javax.swing.*;
import javax.swing.plaf.basic.BasicButtonUI;
import java.awt.*;

/**
 *
 * @author asaas
 */
public class LocadoraVeiculosMainView extends javax.swing.JFrame {

    /**
     * Creates new form LocadoraVeiculosMainView
     */

    private CardLayout cardLayout;

    private ManterClienteController manterClienteController;
    public LocadoraVeiculosMainView() {
        this.manterClienteController = new ManterClienteController(this);
        initComponents();

        this.manterClienteController.init();

        Component[] components = this.getContentPane().getComponents();
        for (Component component : components) {
            if (component instanceof JButton) {
                ((JButton) component).setUI(new BasicButtonUI());
                ((JButton) component).setFocusPainted(false);
            }
        }

        this.cardLayout = (CardLayout) jPanelCards.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSideBar = new javax.swing.JPanel();
        jButtonManterClientes = new javax.swing.JButton();
        jButtonNovoVeiculo = new javax.swing.JButton();
        jButtonLocarVeiculo = new javax.swing.JButton();
        jButtonVenderVeiculo = new javax.swing.JButton();
        jPanelCards = new javax.swing.JPanel();
        jCardManterClientes = new javax.swing.JPanel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField(MaskUtils.getCpfMask());
        jTextFieldRg = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        botaoRemover = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        botaoAtualizar = new javax.swing.JButton();
        jLabelRg = new javax.swing.JLabel();
        botaoAdicionar = new javax.swing.JButton();
        jLabelCpf = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jCardNovoVeiculo = new javax.swing.JPanel();
        jCardLocarVeiculo = new javax.swing.JPanel();
        jCardVenderVeiculo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LocadoraVeiculos");

        jSideBar.setForeground(new java.awt.Color(102, 102, 102));

        jButtonManterClientes.setText("Manter Clientes");
        jButtonManterClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManterClientesActionPerformed(evt);
            }
        });

        jButtonNovoVeiculo.setText("Novo Veículo");
        jButtonNovoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoVeiculoActionPerformed(evt);
            }
        });

        jButtonLocarVeiculo.setText("Locar Veículo");
        jButtonLocarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocarVeiculoActionPerformed(evt);
            }
        });

        jButtonVenderVeiculo.setText("Vender Veículo");
        jButtonVenderVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVenderVeiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jSideBarLayout = new javax.swing.GroupLayout(jSideBar);
        jSideBar.setLayout(jSideBarLayout);
        jSideBarLayout.setHorizontalGroup(
            jSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSideBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonVenderVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLocarVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovoVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonManterClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jSideBarLayout.setVerticalGroup(
            jSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonManterClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonNovoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLocarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonVenderVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(495, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jSideBar);

        jPanelCards.setLayout(new java.awt.CardLayout());

        jTextFieldEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoActionPerformed(evt);
            }
        });

        jTableClientes.setModel(this.manterClienteController.dao);
        jScrollPane2.setViewportView(jTableClientes);

        botaoRemover.setText("Remover");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverremoverListaClientesSelecionados(evt);
            }
        });

        jLabelNome.setText("RG");

        botaoAtualizar.setText("Atualizar");
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizaratualizarListaClientesSelecionados(evt);
            }
        });

        jLabelRg.setText("Nome");

        botaoAdicionar.setText("Adicionar");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionaradicionarCliente(evt);
            }
        });

        jLabelCpf.setText("CPF");

        jLabelEndereco.setText("Endereço");

        javax.swing.GroupLayout jCardManterClientesLayout = new javax.swing.GroupLayout(jCardManterClientes);
        jCardManterClientes.setLayout(jCardManterClientesLayout);
        jCardManterClientesLayout.setHorizontalGroup(
            jCardManterClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCardManterClientesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jCardManterClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCardManterClientesLayout.createSequentialGroup()
                        .addComponent(jLabelRg)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jCardManterClientesLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(botaoAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoRemover)
                        .addGap(18, 18, 18)
                        .addComponent(botaoAtualizar))
                    .addGroup(jCardManterClientesLayout.createSequentialGroup()
                        .addGroup(jCardManterClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCpf)
                            .addComponent(jLabelNome))
                        .addGap(62, 62, 62)
                        .addGroup(jCardManterClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jCardManterClientesLayout.createSequentialGroup()
                        .addComponent(jLabelEndereco)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jCardManterClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );
        jCardManterClientesLayout.setVerticalGroup(
            jCardManterClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCardManterClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jCardManterClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRg)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jCardManterClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jCardManterClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpf)
                    .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jCardManterClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereco)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jCardManterClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRemover)
                    .addComponent(botaoAtualizar)
                    .addComponent(botaoAdicionar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
        );

        jPanelCards.add(jCardManterClientes, "CardManterClientes");

        javax.swing.GroupLayout jCardNovoVeiculoLayout = new javax.swing.GroupLayout(jCardNovoVeiculo);
        jCardNovoVeiculo.setLayout(jCardNovoVeiculoLayout);
        jCardNovoVeiculoLayout.setHorizontalGroup(
            jCardNovoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1054, Short.MAX_VALUE)
        );
        jCardNovoVeiculoLayout.setVerticalGroup(
            jCardNovoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );

        jPanelCards.add(jCardNovoVeiculo, "CardNovoVeiculo");

        javax.swing.GroupLayout jCardLocarVeiculoLayout = new javax.swing.GroupLayout(jCardLocarVeiculo);
        jCardLocarVeiculo.setLayout(jCardLocarVeiculoLayout);
        jCardLocarVeiculoLayout.setHorizontalGroup(
            jCardLocarVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1054, Short.MAX_VALUE)
        );
        jCardLocarVeiculoLayout.setVerticalGroup(
            jCardLocarVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );

        jPanelCards.add(jCardLocarVeiculo, "CardLocarVeiculo");

        javax.swing.GroupLayout jCardVenderVeiculoLayout = new javax.swing.GroupLayout(jCardVenderVeiculo);
        jCardVenderVeiculo.setLayout(jCardVenderVeiculoLayout);
        jCardVenderVeiculoLayout.setHorizontalGroup(
            jCardVenderVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1054, Short.MAX_VALUE)
        );
        jCardVenderVeiculoLayout.setVerticalGroup(
            jCardVenderVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );

        jPanelCards.add(jCardVenderVeiculo, "CardVenderVeiculo");

        jSplitPane1.setRightComponent(jPanelCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonManterClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManterClientesActionPerformed
        cardLayout.show(jPanelCards, "CardManterClientes");
    }//GEN-LAST:event_jButtonManterClientesActionPerformed

    private void jButtonNovoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoVeiculoActionPerformed
        cardLayout.show(jPanelCards, "CardNovoVeiculo");
    }//GEN-LAST:event_jButtonNovoVeiculoActionPerformed

    private void jButtonLocarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocarVeiculoActionPerformed
        cardLayout.show(jPanelCards, "CardLocarVeiculo");
    }//GEN-LAST:event_jButtonLocarVeiculoActionPerformed

    private void botaoRemoverremoverListaClientesSelecionados(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverremoverListaClientesSelecionados
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRemoverremoverListaClientesSelecionados

    private void botaoAtualizaratualizarListaClientesSelecionados(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizaratualizarListaClientesSelecionados
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAtualizaratualizarListaClientesSelecionados

    private void botaoAdicionaradicionarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionaradicionarCliente
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAdicionaradicionarCliente

    private void jTextFieldEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoActionPerformed

    private void jButtonVenderVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVenderVeiculoActionPerformed
        cardLayout.show(jPanelCards, "CardVenderVeiculo");
    }//GEN-LAST:event_jButtonVenderVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocadoraVeiculosMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocadoraVeiculosMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocadoraVeiculosMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocadoraVeiculosMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocadoraVeiculosMainView().setVisible(true);
            }
        });
    }

    public void limpaCampos() {
        this.jTextFieldNome.setText("");
        this.jTextFieldRg.setText("");
        this.jFormattedTextFieldCpf.setText("");
        this.jTextFieldEndereco.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botaoAdicionar;
    public javax.swing.JButton botaoAtualizar;
    public javax.swing.JButton botaoRemover;
    private javax.swing.JButton jButtonLocarVeiculo;
    private javax.swing.JButton jButtonManterClientes;
    private javax.swing.JButton jButtonNovoVeiculo;
    private javax.swing.JButton jButtonVenderVeiculo;
    private javax.swing.JPanel jCardLocarVeiculo;
    public javax.swing.JPanel jCardManterClientes;
    private javax.swing.JPanel jCardNovoVeiculo;
    private javax.swing.JPanel jCardVenderVeiculo;
    public javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRg;
    private javax.swing.JPanel jPanelCards;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jSideBar;
    private javax.swing.JSplitPane jSplitPane1;
    public javax.swing.JTable jTableClientes;
    public javax.swing.JTextField jTextFieldEndereco;
    public javax.swing.JTextField jTextFieldNome;
    public javax.swing.JTextField jTextFieldRg;
    // End of variables declaration//GEN-END:variables
}
